from __future__ import annotations

from typing import Any, Dict, List

from ..support import _camel_case
from ..support import _pascal_case

def _render_action_service(ir: Dict[str, Any]) -> str:
    action_input_by_id = {item["id"]: item for item in ir.get("action_inputs", []) if isinstance(item, dict) and "id" in item}
    action_output_by_id = {item["id"]: item for item in ir.get("action_outputs", []) if isinstance(item, dict) and "id" in item}
    action_output_creators = sorted(
        {
            f"create{_pascal_case(str(shape.get('name', 'Output')))}Event"
            for shape in ir.get("action_outputs", [])
            if isinstance(shape, dict)
        }
    )

    lines: List[str] = [
        "// Code generated by prophet-cli. DO NOT EDIT.",
        "",
        "import type * as Actions from './actions';",
        "import type { ActionContext, ActionHandlers } from './action-handlers';",
        "import { createEventId } from '@prophet-ontology/events-runtime';",
        "import {",
        "  " + ",\n  ".join(action_output_creators + ["publishDomainEvents", "toActionOutcome", "type EventPublisher"]),
        "} from './events';",
        "",
        "export class ActionExecutionService {",
        "  constructor(",
        "    private readonly handlers: ActionHandlers,",
        "    private readonly eventPublisher: EventPublisher,",
        "  ) {}",
        "",
    ]

    for action in sorted(ir.get("actions", []), key=lambda item: str(item.get("id", ""))):
        if not isinstance(action, dict):
            continue
        action_name = str(action.get("name", "action"))
        camel = _camel_case(action_name)
        input_name = _pascal_case(str(action_input_by_id.get(str(action.get("input_shape_id", "")), {}).get("name", "Input")))
        output_name = _pascal_case(str(action_output_by_id.get(str(action.get("output_shape_id", "")), {}).get("name", "Output")))

        lines.append(f"  async {camel}(input: Actions.{input_name}, context: ActionContext): Promise<Actions.{output_name}> {{")
        lines.append(f"    const result = await this.handlers.{camel}.handle(input, context);")
        lines.append(f"    const outcome = toActionOutcome<Actions.{output_name}>(result);")
        lines.append(f"    const events = [create{output_name}Event(outcome.output), ...outcome.additionalEvents];")
        lines.append("    await publishDomainEvents(this.eventPublisher, events, {")
        lines.append("      traceId: context.traceId ?? createEventId(),")
        lines.append(f"      source: context.eventSource ?? '{str(ir.get('ontology', {}).get('name', 'prophet'))}',")
        lines.append("      attributes: context.eventAttributes,")
        lines.append("    });")
        lines.append("    return outcome.output;")
        lines.append("  }")
        lines.append("")

    lines.append("}")
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"
