from __future__ import annotations

from typing import Any, Dict

def _render_index_file(ir: Dict[str, Any]) -> str:
    lines = [
        "// Code generated by prophet-cli. DO NOT EDIT.",
        "",
        "import type { Application } from 'express';",
        "import { buildActionRouter } from './action-routes';",
        "import { buildQueryRouter } from './query-routes';",
        "import { ActionExecutionService } from './action-service';",
        "import { EventEmitterNoOp, type EventEmitter } from './events';",
        "import type { ActionContext, ActionHandlers } from './action-handlers';",
        "import type { Repositories } from './persistence';",
        "",
        "export interface MountDependencies {",
        "  repositories: Repositories;",
        "  handlers: ActionHandlers;",
        "  eventEmitter?: EventEmitter;",
        "}",
        "",
        "export function mountProphet(app: Application, deps: MountDependencies): void {",
        "  const eventEmitter = deps.eventEmitter ?? new EventEmitterNoOp();",
        "  const context: ActionContext = {",
        "    repositories: deps.repositories,",
        "    eventEmitter,",
        "  };",
        "  const service = new ActionExecutionService(deps.handlers, eventEmitter);",
        "  app.use(buildActionRouter(service, context));",
        "  app.use(buildQueryRouter(deps.repositories));",
        "}",
        "",
    ]
    return "\n".join(lines)


