from __future__ import annotations

from typing import Any, Dict

def _render_index_file(ir: Dict[str, Any]) -> str:
    lines = [
        "// Code generated by prophet-cli. DO NOT EDIT.",
        "",
        "import type { Application } from 'express';",
        "import { buildActionRouter } from './action-routes';",
        "import { buildQueryRouter } from './query-routes';",
        "import { ActionExecutionService } from './action-service';",
        "import { NoOpEventPublisher, type EventPublisher } from './events';",
        "import type { ActionContext, ActionHandlers } from './action-handlers';",
        "import type { Repositories } from './persistence';",
        "",
        "export interface MountDependencies {",
        "  repositories: Repositories;",
        "  handlers: ActionHandlers;",
        "  eventPublisher?: EventPublisher;",
        "  eventSource?: string;",
        "  eventAttributes?: Record<string, string>;",
        "}",
        "",
        "export function mountProphet(app: Application, deps: MountDependencies): void {",
        "  const eventPublisher = deps.eventPublisher ?? new NoOpEventPublisher();",
        "  const context: ActionContext = {",
        "    repositories: deps.repositories,",
        "    eventPublisher,",
        f"    eventSource: deps.eventSource ?? '{str(ir.get('ontology', {}).get('name', 'prophet'))}',",
        "    eventAttributes: deps.eventAttributes,",
        "  };",
        "  const service = new ActionExecutionService(deps.handlers, eventPublisher);",
        "  app.use(buildActionRouter(service, context));",
        "  app.use(buildQueryRouter(deps.repositories));",
        "}",
        "",
    ]
    return "\n".join(lines)

